# Global configuration for ReadingRabbit OCR application
video_path: sample.mp4  # placeholder path to input video
output_text_path: output.txt
use_gpu: true
gpu_index: 0
ocr_languages:
  - en
prompt_template: "Correct the OCR text: {text}"
threads: 4
ui_theme: dark
llm_model: t5-small  # Hugging Face model identifier for verification
show_resource_usage: true  # toggle resource monitoring in GUI
monitor_interval: 1.0  # seconds between resource updates
