# Global configuration for ReadingRabbit OCR application
video_path: sample.mp4  # placeholder path to input video on Windows
output_text_path: output/transcript.txt
use_gpu: true
gpu_index: 0
ocr_languages:
  - en
prompt_template: "Correct the OCR text: {text}"
threads: 4
ui_theme: dark
llm_model: t5-small
show_resource_usage: true
monitor_interval: 1.0
resource_history_seconds: 120
resource_chart_height: 160
resource_log_path: logs/resource_history.csv
alert_cooldown_seconds: 45.0
resource_alerts:
  cpu: 95
  ram: 90
  gpu: 90
  vram: 90
themes:
  dark:
    background: "#0b0c10"
    surface: "#1f2833"
    accent: "#45a29e"
    text: "#c5c6c7"
    highlight: "#66fcf1"
    danger: "#ff6b6b"
    font: "Segoe UI"
    font_size: 11
    chart_colors:
      cpu: "#66fcf1"
      ram: "#45a29e"
      gpu: "#ff9f1c"
      vram: "#f15bb5"
  midnight:
    background: "#050608"
    surface: "#10131a"
    accent: "#00c2ff"
    text: "#d8dee9"
    highlight: "#88c0d0"
    danger: "#ff5370"
    font: "Segoe UI"
    font_size: 11
    chart_colors:
      cpu: "#88c0d0"
      ram: "#00c2ff"
      gpu: "#ff9f1c"
      vram: "#c084fc"
